name: nightly restage

on:
  schedule:
    # 3am UTC
    - cron: '0 3 * * *'

jobs:
  restage:
    runs-on: ubuntu-latest
    container: governmentpaas/cf-cli
    steps:
      - name: restage
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_APP: ${{ secrets.CF_APP }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_SPACE_DEV: ${{ secrets.CF_SPACE_DEV }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}

        run: |
          cf login -a $CF_API -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
          cf restage $CF_APP
          cf target -s $CF_SPACE_DEV
          cf stop $CF_APP